/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package irrigate.view;

import java.awt.CardLayout;
import javax.swing.*;
import irrigate.model.Model;
/**
 *
 * @author cyril
 */
public class ViewFrame extends javax.swing.JFrame {

    
    private Model my_model;
    /**
     * Creates new form ViewFrame
     */
    public ViewFrame(Model _model) {
        initComponents();
        my_model = _model;
        this.setUserList(my_model.getUserModel());   
    }
    
    public ViewFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        displayPanel = new javax.swing.JPanel();
        chooseUserPanel = new javax.swing.JPanel();
        userListCombo = new javax.swing.JComboBox();
        chooseUserButton = new javax.swing.JButton();
        farmerPanel = new javax.swing.JPanel();
        farmerName = new javax.swing.JLabel();
        changeUserFarmer = new javax.swing.JButton();
        viewMapButton = new javax.swing.JButton();
        managerPanel = new javax.swing.JPanel();
        managerName = new javax.swing.JLabel();
        changeUserManager = new javax.swing.JButton();
        accountantPanel = new javax.swing.JPanel();
        accountantName = new javax.swing.JLabel();
        changeUserAccountant = new javax.swing.JButton();
        mapViewPanel = new javax.swing.JPanel();
        mapViewLabel = new javax.swing.JLabel();
        componentScrollList = new javax.swing.JScrollPane();
        componentList = new javax.swing.JList();
        chooseComponentButton = new javax.swing.JButton();
        componentViewPanel = new javax.swing.JPanel();
        componentViewLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Irrigation System");
        setBackground(new java.awt.Color(230, 230, 230));

        displayPanel.setLayout(new java.awt.CardLayout());

//        userListCombo.addItem("One");
//        userListCombo.addItem("Two");

        chooseUserButton.setText("Choose User");
        chooseUserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseUserButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout chooseUserPanelLayout = new javax.swing.GroupLayout(chooseUserPanel);
        chooseUserPanel.setLayout(chooseUserPanelLayout);
        chooseUserPanelLayout.setHorizontalGroup(
            chooseUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(chooseUserPanelLayout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(userListCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(chooseUserButton)
                .addContainerGap(165, Short.MAX_VALUE))
        );
        chooseUserPanelLayout.setVerticalGroup(
            chooseUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(chooseUserPanelLayout.createSequentialGroup()
                .addGap(161, 161, 161)
                .addGroup(chooseUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userListCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chooseUserButton))
                .addContainerGap(201, Short.MAX_VALUE))
        );

        displayPanel.add(chooseUserPanel, "chooseUser");

        farmerName.setText("Farmer");

        changeUserFarmer.setText("Change User");
        changeUserFarmer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeUserActionPerformed(evt);
            }
        });

        viewMapButton.setText("View Components Map");
        viewMapButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewMapActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout farmerPanelLayout = new javax.swing.GroupLayout(farmerPanel);
        farmerPanel.setLayout(farmerPanelLayout);
        farmerPanelLayout.setHorizontalGroup(
            farmerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(farmerPanelLayout.createSequentialGroup()
                .addGroup(farmerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(farmerPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(farmerName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(changeUserFarmer))
                    .addGroup(farmerPanelLayout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(viewMapButton)))
                .addContainerGap(143, Short.MAX_VALUE))
        );
        farmerPanelLayout.setVerticalGroup(
            farmerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(farmerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(farmerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(farmerName)
                    .addComponent(changeUserFarmer))
                .addGap(125, 125, 125)
                .addComponent(viewMapButton)
                .addContainerGap(203, Short.MAX_VALUE))
        );

        displayPanel.add(farmerPanel, "farmer");

        managerName.setText("Manager");

        changeUserManager.setText("Change User");
        changeUserManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeUserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout managerPanelLayout = new javax.swing.GroupLayout(managerPanel);
        managerPanel.setLayout(managerPanelLayout);
        managerPanelLayout.setHorizontalGroup(
            managerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(managerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(managerName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(changeUserManager)
                .addContainerGap(249, Short.MAX_VALUE))
        );
        managerPanelLayout.setVerticalGroup(
            managerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(managerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(managerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(managerName)
                    .addComponent(changeUserManager))
                .addContainerGap(351, Short.MAX_VALUE))
        );

        displayPanel.add(managerPanel, "manager");

        accountantName.setText("Accountant");

        changeUserAccountant.setText("Change User");
        changeUserAccountant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeUserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout accountantPanelLayout = new javax.swing.GroupLayout(accountantPanel);
        accountantPanel.setLayout(accountantPanelLayout);
        accountantPanelLayout.setHorizontalGroup(
            accountantPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accountantPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(accountantName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(changeUserAccountant)
                .addContainerGap(236, Short.MAX_VALUE))
        );
        accountantPanelLayout.setVerticalGroup(
            accountantPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accountantPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(accountantPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(accountantName)
                    .addComponent(changeUserAccountant))
                .addContainerGap(351, Short.MAX_VALUE))
        );

        displayPanel.add(accountantPanel, "accountant");

        mapViewLabel.setText("Map View");

        componentScrollList.setViewportView(componentList);

        chooseComponentButton.setText("Choose Component");

        javax.swing.GroupLayout mapViewPanelLayout = new javax.swing.GroupLayout(mapViewPanel);
        mapViewPanel.setLayout(mapViewPanelLayout);
        mapViewPanelLayout.setHorizontalGroup(
            mapViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mapViewPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mapViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mapViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(chooseComponentButton)
                        .addGroup(mapViewPanelLayout.createSequentialGroup()
                            .addComponent(mapViewLabel)
                            .addGap(155, 155, 155)))
                    .addComponent(componentScrollList, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(190, Short.MAX_VALUE))
        );
        mapViewPanelLayout.setVerticalGroup(
            mapViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mapViewPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mapViewLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(componentScrollList, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chooseComponentButton)
                .addGap(18, 18, 18))
        );

        displayPanel.add(mapViewPanel, "mapView");

        componentViewLabel.setText("Component View");

        javax.swing.GroupLayout componentViewPanelLayout = new javax.swing.GroupLayout(componentViewPanel);
        componentViewPanel.setLayout(componentViewPanelLayout);
        componentViewPanelLayout.setHorizontalGroup(
            componentViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(componentViewPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(componentViewLabel)
                .addContainerGap(310, Short.MAX_VALUE))
        );
        componentViewPanelLayout.setVerticalGroup(
            componentViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(componentViewPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(componentViewLabel)
                .addContainerGap(360, Short.MAX_VALUE))
        );

        displayPanel.add(componentViewPanel, "componentView");

        getContentPane().add(displayPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chooseUserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseUserButtonActionPerformed
        farmerName.setText(userListCombo.getSelectedItem().toString());
        // Switch to other view
        CardLayout card = (CardLayout) displayPanel.getLayout();
        card.show(displayPanel, "farmer");

    }//GEN-LAST:event_chooseUserButtonActionPerformed

    private void changeUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeUserActionPerformed
        // Switch to choose user view
        CardLayout card = (CardLayout) displayPanel.getLayout();
        card.show(displayPanel, "chooseUser");
    }//GEN-LAST:event_changeUserActionPerformed

    private void viewMapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewMapActionPerformed
        // Switch to choose user view
        CardLayout card = (CardLayout) displayPanel.getLayout();
        card.show(displayPanel, "mapView");
    }//GEN-LAST:event_viewMapActionPerformed

    public JButton getViewMap() {
        return viewMapButton;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel accountantName;
    private javax.swing.JPanel accountantPanel;
    private javax.swing.JButton changeUserAccountant;
    private javax.swing.JButton changeUserFarmer;
    private javax.swing.JButton changeUserManager;
    private javax.swing.JButton chooseComponentButton;
    private javax.swing.JButton chooseUserButton;
    private javax.swing.JPanel chooseUserPanel;
    private javax.swing.JList componentList;
    private javax.swing.JScrollPane componentScrollList;
    private javax.swing.JLabel componentViewLabel;
    private javax.swing.JPanel componentViewPanel;
    private javax.swing.JPanel displayPanel;
    private javax.swing.JLabel farmerName;
    private javax.swing.JPanel farmerPanel;
    private javax.swing.JLabel managerName;
    private javax.swing.JPanel managerPanel;
    private javax.swing.JLabel mapViewLabel;
    private javax.swing.JPanel mapViewPanel;
    private javax.swing.JComboBox userListCombo;
    private javax.swing.JButton viewMapButton;
    // End of variables declaration//GEN-END:variables

    public void setComponentList(ListModel lm) {
        componentList.setModel(lm);        
    }

    public void setUserList(ComboBoxModel cb) {
        userListCombo.setModel(cb);        
    }

    
    public JButton getUserView() {
        return chooseUserButton;
    }
}
